config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'report/pending_service'
  get 'report/pending_bill'
  get 'report/service_catagory'

  resources :operators

  resources :icares do
    member do
      patch :assign_task
      patch :operator
    end
    collection do
      get :admin_index
    end
  end

  resources :icare_types

  resources :salary_invoices

  resources :salaries do
    member do
      patch :custom_paid
    end
  end

  resources :wallets

  resources :invoices

  resources :bills do
    member do
      patch :custom_paid
    end
  end

  resources :customers do
    member do
      post :active
      get :basic_info
      get :address
      get :login_info
    end
  end

  resources :packages

  resources :employees

  resources :roles

  resources :zones

  resources :organizations do
    resources :connections
    member do
      patch :logo
    end
  end

  
  resources :districts do
    get "delete"
    resources :areas
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'admins' => 'users#admin'

  match '/singup',     to: 'users#new',              via: 'get'
  match '/signin',     to: 'sessions#new',           via: 'get'
  match '/signout',    to: 'sessions#destroy',       via: 'delete'

  resources :users do
    member do
      patch :upload
      patch :customer_upload
      patch :employee_upload
    end
  end

  root "home#index"

  get 'dashboard'=>'home#dashboard'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_one :user, as: :meta, dependent: :destroy
	belongs_to 	:organization
	has_many 	:salaries
	has_one 	:wallet, as: :fee, dependent: :destroy
	has_many 	:icares
	belongs_to 	:role
	has_many 	:operators

	validates :batch_number, numericality: { only_integer: true }, :uniqueness => {:scope => :organization_id,:case_sensitive => false}
	validates :address, presence: true
	validates :join_date, presence: true
	validates :basic_salary, presence: true, numericality: true

	validates :first_name, presence: true
	validates :email, presence: true
	validates :mobile, presence: true
	validates :role, presence: true

	accepts_nested_attributes_for :user
	accepts_nested_attributes_for :wallet

# 	belongs_to :boss, :class_name => "Employee"
#  	has_many :reports, :class_name => "Employee", :foreign_key => "boss_id"

	def full_name
		"#{self.first_name}" " " "#{self.last_name}"
	end

	def self.search(search)
	  if search
	    where('batch_number LIKE ? OR first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR (first_name || " " || last_name) LIKE ?', 
	    	"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}")
	  else
	    all
	  end
	end

	def total
		self.basic_salary.to_f+self.additional_salary.to_f
	end

	def salary
	   "%.2f TK" % self.total
	end

	def is_monthly_salary_exist(monthly)
		@salaries = self.salaries

		if @salaries.nil?
			false
		else
			salary = self.salaries.where("strftime('%m%Y', month_year) = ?", "#{monthly}").first
			if salary.nil?
				false
			else
				true
			end
		end
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	layout "dashboard"
	before_action :set_employee, only: [:edit, :update, :show]
	before_action :authenticate_user!
	before_action :check_customer
	before_action :set_role

	def index
		@employees = current_organization.employees.search(params[:search])
	end

	def new
		@employee = Employee.new
		@employee.build_user unless @employee.user
		@employee.build_wallet unless @employee.wallet
	end

	def create
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path
		else
			render 'new'
		end
	end

	def edit
	end

	def show
	end

	def update
     	if @employee.update_attributes(employee_params)
            flash[:notice] = "Employee updated successfully."
            redirect_to edit_employee_path(@employee)
        else
            render :action => 'edit'
        end
	end

	private 
		def employee_params
			params.require(:employee).permit(:first_name, :last_name, :mobile, :email, :organization_id, 
				:batch_number, :address, :basic_salary, :additional_salary, :join_date, :role_id, 
				wallet_attributes: [:amount], user_attributes: [:id, :organization_id, :username, :password, :password_confirmation, :role])
		end

		def update_employee_params
			params.require(:employee).permit(:first_name, :last_name, :mobile, :email, :organization_id, :batch_number, :address, :basic_salary, :additional_salary, :join_date)
		end

		def set_employee
			@employee = Employee.find(params[:id])
		end

		def set_role
			check_role("employee")
		end
end

app/views/employees/_employee.html.erb
<% @employees.each do |employee| %>
	<tr>
		<td><%= employee.batch_number %></td>
		<td><%= employee.first_name %> <%= employee.last_name %></td>
		<td><%= employee.email %></td>
		<td><%= employee.mobile %></td>
		<td><%= employee.address %></td>
		<td><%= employee.role.name %></td>
		<td><%= employee.join_date %></td>
		<td><%= employee.total %></td>
		<td><%= employee.wallet.amount %></td>
		<td>
			<% if employee.status == 1 %>
				<span class="label label-success">active</span>
			<% else %>
				<span class="label label-danger">active</span>
			<% end %>
		</td>
		<td><%= link_to("Edit", edit_employee_path(employee), class: "btn") %></td>
	</tr>
<% end %>

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>

	<%= render 'shared/error_message', object: f.object %>

	<%= f.hidden_field :organization_id, value: current_organization.id %>
	

	<fieldset>
		<legend>Basic Infomation</legend>
		<div class="form-group">
			<%= f.label :batch_number  %><br>
			<%= f.text_field :batch_number, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :first_name %><br>
			<%= f.text_field :first_name, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :last_name %><br>
			<%= f.text_field :last_name, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :email %><br>
			<%= f.text_field :email, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :mobile %><br>
			<%= f.text_field :mobile, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :role_id, "Role" %><br/>
			<%= f.collection_select(:role_id, current_organization.roles.order(:name), :id, :name, {include_blank: true}, {:class=>'form-control'}) %>
		</div>

	</fieldset>

	<%= f.fields_for :wallet do |w| %>
		<%= w.hidden_field :amount, value: 0 %>
	<% end %>

	<%= f.fields_for :user do |u| %>
		<fieldset>
			<legend>Login Infomation</legend>

			<%= u.hidden_field :role, value: "employee" %>
			<%= u.hidden_field :organization_id, value: current_organization.id %>
			
		  	<div class="form-group">
				<%= u.label :username %><br>
				<%= u.text_field :username, autofocus: true, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= u.label :password %><br>
				<%= u.password_field :password, autofocus: true, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= u.label :password %><br>
				<%= u.password_field :password_confirmation, autofocus: true, class: "form-control" %>
			</div>
		</fieldset>
	<% end %>

	<fieldset>
		<legend>Location And Join Date</legend>
		<div class="form-group">
			<%= f.label :address %><br>
			<%= f.text_field :address, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :join_date %><br>
			<%= f.date_field :join_date,  autofocus: true, class: "form-control" %>
		</div>
	</fieldset>

	<fieldset>
		<legend>Salary Infomation</legend>
		<div class="form-group">
			<%= f.label :basic_salary %><br>
			<%= f.text_field :basic_salary, autofocus: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :additional_salary %><br>
			<%= f.text_field :additional_salary, autofocus: true, class: "form-control" %>
		</div>
	</fieldset>

	<%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/employees/edit.html.erb
<% if !current_user.is_employee %>
	<!-- header -->
	<div class="header">
	    <h1 class="page-title"><%= @employee.full_name %></h1>
	    <ul class="breadcrumb">
	        <li><%= link_to("Employees", employees_path) %></li>
	        <li class="active">Edit</li>
	    </ul>
	</div>  	
	<!-- header -->	
<% end %>


<div class="col-md-12">
	<div class="row">
	<%= render "shared/flash_message" %>
	<div class="flash"></div>
		<!-- right side -->
		<div class="col-md-3 col-xs-12 pull-right">
			<!-- profile picture	 -->
		    <%= image_tag("profile.jpg") %>
			<!-- profile picture	 -->

			<!-- Button trigger modal -->
			<% if current_user.id == @employee.user.id %>
				<button class="btn btn-link" data-toggle="modal" data-target="#myModal">
				  Change Picture
				</button>
			<% end %>

			<div class="pull-right">
				<% if @employee.status == 1 %>
					<span class="label label-success">active</span>	
				<% else %>
					<span class="label label-danger">deactive</span>	
				<% end %>
			</div>
			
		</div>
		<!-- right side -->

		<!-- left side -->
		<div class="col-md-9 pull-left">
			
			<ul class="nav nav-pills" role="tablist" id="myTab">
			  <li class="active"><a href="#employee_basic_info" role="tab" data-toggle="tab">Basic Info</a></li>
			  
			  <li><a href="#employee_login_info" role="tab" data-toggle="tab">Login Info</a></li>
			</ul>

			<div class="tab-content">


				<div class="tab-pane active" id="employee_basic_info">
					<%= render "employees/edit/basic" %>
				</div>
				<div class="tab-pane" id="employee_login_info">
					<%= render "employees/edit/login_info" %>
				</div>

			</div>

		</div>
		<!-- left side -->

	</div>
</div>




<% if current_user.id == @employee.user.id %>
	<!-- Modal -->
	<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-sm">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
	      </div>
	      <div class="modal-body">
	        <%= form_for current_user, url: employee_upload_user_path(current_user) do |f| %>
			  
				<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
			  <div class="form-group">
			  	<%= f.label :image %><br />
			  	<%= f.file_field :image %>
			  	  
			  </div>

			  <%= f.submit "Save", disable_with: 'Saveing...', class: "btn btn-primary" %>
			<% end -%>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/employees/index.html.erb
<div class="header">
    <%= render 'shared/notification' %>

    <h1 class="page-title">Employees</h1>
    <ul class="breadcrumb">
        <li><%= link_to("Home", dashboard_path) %></li>
        <li class="active">Employees</li>
    </ul>
</div>


<div class="col-sm-12">
	<div class="col-sm-3">
		<div class="pull-left">
			<% if current_user.is_admin || current_employee.role.employee %>
				<%= link_to new_employee_path, class: "btn btn-info" do %>
					<i class="glyphicon glyphicon-plus"></i> New Employee
				<% end %>	
			<% end %>
			
		</div>	
	</div>
	<div class="col-sm-5">
		<%= form_tag employees_path, :method => 'get', remote: true, :id => "employees_search" do %>
			<div class="input-group">
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>	
				<div class="input-group-btn">
					<%= button_tag(class: "btn btn-default") do %>
						<i class="glyphicon glyphicon-search"></i>
					<% end %>
				</div>
			</div>
		<% end %>
		<br>
	</div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Employee ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>Mobile</th>
				<th>Address</th>
				<th>Role</th>
				<th>Join Date</th>
				<th>Salary</th>
				<th>Wallet</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody id="employees">
			<%= render "employee" %>
		</tbody>
	</table>
</div>

app/views/employees/index.js.erb
$("#employees").html("<%= escape_javascript(render("employee")) %>");

app/views/employees/new.html.erb
<div class="col-sm-7">
	<h2>New Employee</h2>
	<%= render "form" %>	
</div>

app/views/employees/show.html.erb
<% if !current_user.is_employee %>
	<!-- header -->
	<div class="header">
	    <div class="stats">
	    	<span class="label label-success">Wallet: <%= @employee.wallet.amount %></span>
	    </div>

	    <h1 class="page-title"><%= @employee.full_name %></h1>
	    <ul class="breadcrumb">
	        <li><%= link_to("employees", employees_path) %></li>
	        <li class="active">Profile</li>
	    </ul>
	</div>  	
	<!-- header -->
<% end %>

<div class="col-md-12">
	<div class="row">

		<!-- right side -->
		<div class="col-md-3 col-xs-12 pull-right">
			<!-- profile picture	 -->
		    <%= image_tag("profile.jpg") %>
			<!-- profile picture	 -->

			<div class="pull-right">
				<% if @employee.status == 1 %>
					<span class="label label-success">active</span>	
				<% else %>
					<span class="label label-danger">deactive</span>	
				<% end %>
				
			</div>

			<h3>General Information</h3>
			<table class="table">
				<tr>
					<td>employee ID</td>
					<td><%= @employee.batch_number %></td>
				</tr>
				<tr>
					<td>Salary</td>
					<td><%= @employee.salary %></td>
				</tr>
				<tr>
					<td>Join Date</td>
					<td><%= @employee.join_date.strftime("%d-%m-%Y") %></td>
				</tr>
			</table>

			<h3>Contact Information</h3>
			<table class="table">
				<tr>
					<td><i class="fa fa-phone"></i> Mobile</td>
					<td><%= @employee.mobile %></td>
				</tr>
				<tr>
					<td><i class="fa fa-envelope"></i> Email</td>
					<td><%= @employee.email %></td>
				</tr>
				<tr>
					<td><i class="fa fa-map-marker">Address</td>
					<td>
						<%= @employee.address %>
					</td>
				</tr>
			</table>

		</div>
		<!-- right side -->

		<!-- left side -->
		<div class="col-md-9 pull-left">
		<h2>Salary Information</h2>
		  	<table class="table table-striped table-bordered">
		  		<thead>
		  			<tr>
		  				<th>Date</th>
		  				<th>Debit</th>
		  				<th>Credit</th>
		  			</tr>
		  		</thead>
		  		<tbody>
		  			<% @salaries = @employee.salaries.order(updated_at: :desc) %>
		  			<% @salaries.each do |salary| %>
		  				<tr>
		  					<td><%= salary.updated_at.strftime("%d-%m-%Y") %></td>
		  					<td><%= salary.debit %></td>
		  					<td><%= salary.credit %></td>
		  				</tr>
		  			<% end %>
		  		</tbody>
		  	</table>
		</div>
		<!-- left side -->
			  
	</div>
</div>

app/views/employees/update.js.erb
$("#employee_basic_info").html("<%= escape_javascript(render 'employees/edit/basic') %>")
$("#employee_login_info").html("<%= escape_javascript(render 'employees/edit/login_info') %>")
$(".flash").html("<%= escape_javascript(render "shared/flash_message") %>")