config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'report/pending_service'
  get 'report/pending_bill'
  get 'report/service_catagory'

  resources :operators

  resources :icares do
    member do
      patch :assign_task
      patch :operator
    end
    collection do
      get :admin_index
    end
  end

  resources :icare_types

  resources :salary_invoices

  resources :salaries do
    member do
      patch :custom_paid
    end
  end

  resources :wallets

  resources :invoices

  resources :bills do
    member do
      patch :custom_paid
    end
  end

  resources :customers do
    member do
      post :active
      get :basic_info
      get :address
      get :login_info
    end
  end

  resources :packages

  resources :employees

  resources :roles

  resources :zones

  resources :organizations do
    resources :connections
    member do
      patch :logo
    end
  end

  
  resources :districts do
    get "delete"
    resources :areas
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'admins' => 'users#admin'

  match '/singup',     to: 'users#new',              via: 'get'
  match '/signin',     to: 'sessions#new',           via: 'get'
  match '/signout',    to: 'sessions#destroy',       via: 'delete'

  resources :users do
    member do
      patch :upload
      patch :customer_upload
      patch :employee_upload
    end
  end

  root "home#index"

  get 'dashboard'=>'home#dashboard'

end

app/models/zone.rb
class Zone < ActiveRecord::Base
	belongs_to :organization
	has_many :customer
	has_many :connections

	validates :name, presence: true
	validates_uniqueness_of :name, :scope => :organization_id, :case_sensitive=>false
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	layout "dashboard"

	before_action :authenticate_user!
	before_action :check_customer
	before_action :set_role #acountant, admin
	
	def index
		@customers 	= current_organization.customers.where(active: true)
		
		if params[:month_year].present?
			hash 	= params[:month_year]
			@d 		= Date.new(hash['(1i)'].to_i, hash['(2i)'].to_i, hash['(3i)'].to_i)
			@date 	= Date.parse(@d.to_s)
			@my 	= Date.parse(@d.to_s).strftime("%m%Y")
		else
			@date 	= Time.now
			@my 	= Time.now.strftime("%m%Y")
		end
	end

	private
		def set_role
		    check_role("accountant")
		end
end

app/views/invoices/_invoice.html.erb
<% @customers.each do |customer| %>
	
	<% if !customer.is_monthly_bill_exist(@my) %>
		<tr>
			<td>
				<%= check_box_tag "customer_ids[]", customer.id %>
			</td>
			<td><%= customer.first_name %> <%= customer.last_name %></td>
			<td><%= customer.mobile %></td>
			<td><%= customer.email %></td>
			<td><%= customer.package.f_price %></td>
		</tr>	
	<% end %>
<% end %>

app/views/invoices/_invoice_generator.erb
<%= hidden_field :month_year, value: @date %>
<%= button_tag "Generate Invoice", class: "btn btn-success", id: "generator", :disable_with => 'Generateing...' %>  

app/views/invoices/index.html.erb
<!-- header -->
	<div class="header">
	    <%= render 'shared/notification' %>

	    <h1 class="page-title">Invoice</h1>
	    <ul class="breadcrumb">
	        <li><%= link_to("Customers", customers_path) %></li>
	        <li class="active">Invoice</li>
	    </ul>
	</div>  	
<!-- header -->


<div class="col-sm-8">
	<section class="panel panel-default">
		<%= form_tag Bill.new do |f| %>
			<header class="panel-heading">
				<div class="panel-title">
					Customer List
					<div class="row" style="float: right; margin-top: -8px;">
						<div id="render_generator">
							<%= render "invoice_generator" %>		
						</div>
					</div>
				</div>
				
			</header>
			<div class="panel-body">
				
				<div class="row">
					<table class="table table-hover">
						<thead>
							<tr>
								<th class="select-all-checkbox"><input type="checkbox" id="checkAll" /></th>
								<th>Name</th>
								<th>Mobile</th>
								<th>Email</th>
								<th>Monthly Fee</th>
							</tr>
						</thead>
						<tbody id="invoices">
							<%= render 'invoice' %>
						</tbody>
					</table>
				</div>
			</div>
		<% end %>
	</section>

</div>



<div class="col-sm-4">
	<section class="panel panel-default">
		<header class="panel-heading">
			<h3 class="panel-title">Generate Invoice</h3>
		</header>
		<div class="panel-body">
			<%= form_tag invoices_path, remote: true, :method => 'get', :id => "month_year" do %>
				<%= date_select :month_year, [], order: [:month, :year] %>	
				<%= button_tag "Search", {class: "monthly_customer"} %>
			<% end %>
		</div>
	</section>
</div>

app/views/invoices/index.js.erb
$("#invoices").html("<%= escape_javascript(render('invoice')) %>")
$("#render_generator").replaceWith("<%= escape_javascript(render('invoice_generator')) %>")