config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'report/pending_service'
  get 'report/pending_bill'
  get 'report/service_catagory'

  resources :operators

  resources :icares do
    member do
      patch :assign_task
      patch :operator
    end
    collection do
      get :admin_index
    end
  end

  resources :icare_types

  resources :salary_invoices

  resources :salaries do
    member do
      patch :custom_paid
    end
  end

  resources :wallets

  resources :invoices

  resources :bills do
    member do
      patch :custom_paid
    end
  end

  resources :customers do
    member do
      post :active
      get :basic_info
      get :address
      get :login_info
    end
  end

  resources :packages

  resources :employees

  resources :roles

  resources :zones

  resources :organizations do
    resources :connections
    member do
      patch :logo
    end
  end

  
  resources :districts do
    get "delete"
    resources :areas
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'admins' => 'users#admin'

  match '/singup',     to: 'users#new',              via: 'get'
  match '/signin',     to: 'sessions#new',           via: 'get'
  match '/signout',    to: 'sessions#destroy',       via: 'delete'

  resources :users do
    member do
      patch :upload
      patch :customer_upload
      patch :employee_upload
    end
  end

  root "home#index"

  get 'dashboard'=>'home#dashboard'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  belongs_to :organization
  belongs_to :meta, polymorphic: true

  has_secure_password

  before_save { self.username = username.downcase }
  before_create :create_remember_token
  validates :username, presence: true, :uniqueness => {:case_sensitive => false}

  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :password, :presence     => true,
                     :confirmation => true,
                     :length       => { :minimum => 6 },
                     :if           => :password
  
  # mount_uploader :image, ImageUploader

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def is_super_admin
  	return true if self.role == "super_admin"
  end

  def is_admin
  	return true if self.role == "admin"
  end

  def is_customer
    return true if self.role == "customer"
  end

  def is_employee
    return true if self.role == "employee"
  end

  def self.search(search)
    if search
      where('first_name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  private 
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :set_layout
  respond_to :html, :js
  before_action :authenticate_user!
  # before_action :check_customer
  # before_action :set_super_admin

  skip_before_filter :verify_authenticity_token, :only => :upload
  def admin
  	@admins = User.where(role: "admin")
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(params.require(:user).permit(:password, :password_confirmation, :image))
  		flash[:success] = "Successfully"
  		redirect_to edit_user_path(@user)	
  	else
  		render 'edit'
  	end
  	
  end

  def upload
  	@user = User.find(params[:id])
  	@user.update_attributes(params.require(:user).permit(:image))
  	redirect_to edit_user_path(@user)
  end

  def customer_upload
    current_user.update_attributes(params.require(:user).permit(:image))
    @customer = Customer.find(current_user.meta_id)
    redirect_to edit_customer_path(@customer)
  end

  def employee_upload
    current_user.update_attributes(params.require(:user).permit(:image))
    @employee = Employee.find(current_user.meta_id)
    redirect_to edit_employee_path(@employee)
  end

  private
    def set_layout
      if current_user.is_customer
        "application"
      else
        "dashboard"
      end
    end
  
end

app/views/users/_user.html.erb
<% @admins.each_with_index do |admin, i| %>
	<tr>
		<td><%= i+1 %></td>
		<td><%= admin.first_name %></td>
		<td><%= admin.last_name %></td>
		<td><%= admin.mobile %></td>
		<td><%= admin.email %></td>
		<td><%= admin.username %></td>
		<td>company name</td>
	</tr>
<% end %>

app/views/users/admin.html.erb
<div class="header">
            
    <h1 class="page-title">Users</h1>
    <ul class="breadcrumb">
        <li><%= link_to("Home", dashboard_path) %></li>
        <li class="active">Users</li>
    </ul>
</div>


<div class="btn-toolbar list-toolbar">
	<%= link_to(new_user_path, class: "btn btn-primary") do %>
		<i class="fa fa-plus"></i> New User
	<% end %>
  <div class="btn-group">
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
	  <th>Mobile</th>
      <th>Email</th>
      <th>Username</th>
      <th>Company Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'user' %>
  </tbody>
</table>

<ul class="pagination">
  
</ul>

app/views/users/edit.html.erb
<div class="well">
	<div class="row">
		<%= render "shared/flash_message" %>
		<div class="col-sm-3">
			<div class="thumbnail">

				<%= image_tag('profile.jpg')  %>
		    	<!-- Button trigger modal -->
				
				<div data-toggle="modal" class="btn btn-link" data-target="#admin_pic">
				  Change Picture
				</div>
		    </div>
		</div>

		<div class="col-sm-4">
			<%= form_for @user do |f| %>
				<%= render 'shared/error_message', object: f.object %>
			  <div class="form-group">
			  	<%= f.label :password %><br />
			  	<%= f.password_field :password, class: "form-control" %>
			  </div>

			  <div class="form-group">
			  	<%= f.label :password_confirmation %><br />
			  	<%= f.password_field :password_confirmation, class: "form-control" %>
			  </div>

			  <%= f.submit "Save", disable_with: 'Saveing...', class: "btn btn-primary" %>
			<% end -%>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="admin_pic" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body">
        <%= form_for current_user, url: upload_user_path(current_user) do |f| %>
			<%= render 'shared/error_message', object: f.object %>
		  
			<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
		  <div class="form-group">
		  	<%= f.label :image %><br />
		  	<%= f.file_field :image %>
		  	  
		  </div>

		  <%= f.submit "Save", disable_with: 'Saveing...', class: "btn btn-primary" %>
		<% end -%>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.