config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'report/pending_service'
  get 'report/pending_bill'
  get 'report/service_catagory'

  resources :operators

  resources :icares do
    member do
      patch :assign_task
      patch :operator
    end
    collection do
      get :admin_index
    end
  end

  resources :icare_types

  resources :salary_invoices

  resources :salaries do
    member do
      patch :custom_paid
    end
  end

  resources :wallets

  resources :invoices

  resources :bills do
    member do
      patch :custom_paid
    end
  end

  resources :customers do
    member do
      post :active
      get :basic_info
      get :address
      get :login_info
    end
  end

  resources :packages

  resources :employees

  resources :roles

  resources :zones

  resources :organizations do
    resources :connections
    member do
      patch :logo
    end
  end

  
  resources :districts do
    get "delete"
    resources :areas
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'admins' => 'users#admin'

  match '/singup',     to: 'users#new',              via: 'get'
  match '/signin',     to: 'sessions#new',           via: 'get'
  match '/signout',    to: 'sessions#destroy',       via: 'delete'

  resources :users do
    member do
      patch :upload
      patch :customer_upload
      patch :employee_upload
    end
  end

  root "home#index"

  get 'dashboard'=>'home#dashboard'

end

app/models/salary.rb
class Salary < ActiveRecord::Base
	belongs_to :organization
	belongs_to :employee

	def self.search(date, batch_number)
		if date.present? && batch_number.present?
			employee = Employee.find_by_batch_number("#{batch_number}".to_i)
			where("strftime('%m%Y', month_year) = ? AND employee_id = ?", "#{date}", "#{employee.id}")
		elsif date.present?
			where("strftime('%m%Y', month_year) = ?", "#{date}")
		else
			all
		end
	end
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
	layout "dashboard"
	respond_to :html, :js

	before_action :authenticate_user!
	before_action :check_customer
	before_action :set_salaries, only: [:index, :update, :destroy]
	before_action :set_role
	
	def index
	end

	def create
		@employees = Employee.find(params[:employee_ids])
		if @employees.present?
			@employees.each do |employee|
				@wallet = employee.wallet.amount
				@salary = employee.salary

				if @wallet.to_f>=@salary.to_f
					Salary.create(organization_id: current_organization.id, employee_id: employee.id,  
							month_year: Date.parse(params[:month_year].to_s), debit: employee.salary, 
							credit: @salary.to_f)

					employee.wallet.update_attributes(amount: (@salary.to_f-@wallet.to_f))
				elsif @wallet.to_f<@salary.to_f 
					if @wallet.to_f>0
						Salary.create(organization_id: current_organization.id, employee_id: employee.id,  
							month_year: Date.parse(params[:month_year].to_s), debit: employee.salary, 
							credit: @wallet.to_f)
					else
						Salary.create(organization_id: current_organization.id, employee_id: employee.id,  
							month_year: Date.parse(params[:month_year].to_s), debit: employee.salary, 
							credit: 0)
					end
					employee.wallet.update_attributes(amount: @salary.to_f-@wallet.to_f)
				end
			end	
			redirect_to salaries_path
		end
	end

	def update
		@bill = Salary.find(params[:id])

		@wallet = @bill.employee.wallet.amount
		@bill.update_attributes(credit: @wallet.to_f)
		@bill.employee.wallet.update_attributes(amount: 0)
	end

	def custom_paid
		@salary = Salary.find(params[:id])
		@previous_credit = @salary.credit #take the prevoice credit and add with the wallet
		@salary.update_attributes(params.require(:salary).permit(:credit)) 
		@wallet = (@salary.employee.wallet.amount.to_f+@previous_credit.to_f)-@salary.credit.to_f
		@salary.employee.wallet.update_attributes(amount: @wallet)
	end

	def destroy
		@salary = Salary.find(params[:id])
		@wallet = @salary.employee.wallet.amount.to_f-@salary.debit.to_f
		@salary.employee.wallet.update_attributes(amount: @wallet)
		@salary.destroy
	end

	private
		def salary_params
			params.require(:salary).permit(:organization_id, :customer_id, :date, :credit, :debit)
		end


		def set_salaries
			if params[:month_year].present?
				hash = params[:month_year]
				@d 	= Date.new(hash['(1i)'].to_i, hash['(2i)'].to_i, hash['(3i)'].to_i)
				@my = Date.parse(@d.to_s).strftime("%m%Y")
				@salaries = current_organization.salaries.search(@my, params[:batch_number])
				if !@salaries.nil?
					@salaries = @salaries.paginate(page: params[:page], per_page: 50)
				end
			else
				@my = Time.now.strftime("%m%Y")
				@salaries = current_organization.salaries.search(@my, params[:batch_number]).paginate(page: params[:page], per_page: 50)
			end
		end

		# def paid(wallet, paid)
		# 	wallet.to_f+paid.to_f
		# end

		def set_role
		    check_role("accountant")
		end
end

app/views/salaries/_change_month.html.erb
<% if params[:month_year].nil? %>

	<%= Time.now.strftime("%B %Y") %>
<% else %>
<% @date = Date.new(params[:month_year]['(1i)'].to_i, params[:month_year]['(2i)'].to_i, params[:month_year]['(3i)'].to_i) %>
	<%= @date.strftime("%B %Y") %>
<% end %>

app/views/salaries/_salary.html.erb
<% if @salaries.present? %>
	<% @salaries.each do |salary| %>
		<% if salary.credit==0 %>
			<tr>
				<td><%= salary.employee.batch_number %></td>
				<td><%= salary.employee.full_name %></td>
				<td><%= salary.debit %></td>
				<td><%= salary.credit %></td>
				<td><%= salary.employee.wallet.amount %></td>
				<td>
					<div class="left">
						<%= form_for salary, remote: true, id: "paid_form" do |f| %>
						
						  	<%= button_tag(type: 'submit', class: "btn") do %>
								<font size="2px;"><i class="glyphicon glyphicon-ok"></i></font>
							<% end %>
						<% end -%>
					</div>
					<div class="left">
						<span class="btn glyphicon glyphicon-edit" data-toggle="modal" data-target="#salary-<%= salary.id %>"></span>
					</div>
					<div class="left">
						<%= form_for salary, remote: true, method: "Delete" do |f| %>
							<%= button_tag(type: 'submit', class: "btn") do %>
								<font size="2px;"><i class="glyphicon glyphicon-trash"></i></font>
							<% end %>	  
						<% end -%>	
					</div>
				</td>
			</tr>
		<% elsif salary.credit.to_f < salary.debit.to_f %>
			<tr class="danger">
				<td><%= salary.employee.batch_number %></td>
				<td><%= salary.employee.full_name %></td>
				<td><%= salary.debit %></td>
				<td><%= salary.credit %></td>
				<td><%= salary.employee.wallet.amount %></td>
				<td>
					<div class="left">
						<span class="btn glyphicon glyphicon-edit" data-toggle="modal" data-target="#salary-<%= salary.id %>"></span>
					</div>
				</td>
			</tr>
		<% else %>
			<tr class="success">
				<td><%= salary.employee.batch_number %></td>
				<td><%= salary.employee.full_name %></td>
				<td><%= salary.debit %></td>
				<td><%= salary.credit %></td>
				<td><%= salary.employee.wallet.amount %></td>
				<td>
					<div class="left">
						<span class="btn glyphicon glyphicon-edit" data-toggle="modal" data-target="#salary-<%= salary.id %>"></span>
					</div>
				</td>
			</tr>
		<% end %>


		<div class="modal fade bs-example-modal-sm" id="salary-<%= salary.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog modal-sm">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="myModalLabel"><%= salary.employee.batch_number %>-<%= salary.employee.full_name %></h4>
		      </div>
		      	<%= form_for salary, url: custom_paid_salary_path(salary), remote: true do |f| %>
		      		<div class="modal-body">
		        	
						<%= f.text_field :credit, value: salary.credit %>
					  	
					
		      		</div>
				    <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				        <%= f.submit "Save", disable_with: 'Saveing...', class: "btn btn-primary" %>
				    </div>
		      	<% end -%>
		    </div>
		  </div>
		</div>
	<% end %>
<% end %>

app/views/salaries/custom_paid.js.erb
$('#salary_advance_search').submit()
$("#employee_change_date").html("<%= escape_javascript( render 'salary' ) %>");

app/views/salaries/destroy.js.erb
$('#employee_advance_search').submit()
$("#salaries").html("<%= escape_javascript( render 'salary' ) %>")

app/views/salaries/index.html.erb
<!-- header -->
<div class="header">
    <%= render 'shared/notification' %>

    <h1 class="page-title">Employee Salary</h1>
    <ul class="breadcrumb">
        <li><%= link_to("Home", dashboard_path) %></li>
        <li class="active">Salary</li>
    </ul>
</div>  	
<!-- header -->

<div class="col-sm-9">
	<section class="panel panel-default">
		<header class="panel-heading">
			<div class="panel-title">
				Salary
				<div class="pull-right">
					<div id="change_salary_date">
						<%= render 'change_month' %>
					</div>
				</div>
			</div>
		</header>
		<div class="panel-body">
			<div class="row">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Employee ID</th>
							<th>Name</th>
							<th>Salary</th>
							<th>Paid</th>
							<th>Account</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody id="salaries">
						<%= render 'salary' %>
					</tbody>
				</table>
				<% if @salaries.present? %>
					<%= will_paginate %>	
				<% end %>
			</div>
			
		</div>
	</section>
</div>

<div class="col-sm-3">
	<section class="panel panel-default">
		<header class="panel-heading">
			<h3 class="panel-title">Advance Search</h3>
		</header>
		<%= @cust_id %>
		<div class="panel-body">
			<%= form_tag salaries_path, remote: true, :method => 'get', :id => "salary_advance_search" do %>

				<div class="form-group">
					<%= date_select :month_year, [], order: [:month, :year] %>
				</div>
				<%= text_field_tag :batch_number, [], class: "form-control", placeholder: "Salary ID" %><br />

				<%= button_tag "Search", {class: "btn btn-primary"} %>
			<% end %>
		</div>
	</section>
</div>

app/views/salaries/index.js.erb
$("#salaries").html("<%= escape_javascript( render 'salary' ) %>")
$("#change_salary_date").html("<%= escape_javascript(render 'change_month') %>")

app/views/salaries/update.js.erb
$('#employee_advance_search').submit()
$("#salaries").html("<%= escape_javascript( render 'salary' ) %>")